### ISSUE TITLE
Part of the code is missing...

### ISSUE THREAD

**Issue by judiebig** [xyjigsaw/CENET#1]
Firstly, congrats your paper has been accepted in AAAI 2023, and appreciate your elegant work on the task of knowledge graph reasoning!

I'm trying to reproduce your result according to your repo,  but I found some key files are missing, e.g., main.py.

It would be greatly appreciated if you could provide the full code.

**Comment by xyjigsaw** [comment]
Thank you for your consideration. We are still cleaning the code. 
We will publish a complete version as soon as possible.
