### ISSUE TITLE
#Data file read issues！

### ISSUE THREAD

**Issue by goodboy-yuan** [xyjigsaw/CENET#16]
您好，请问这个错误是因为读取数据文件时的原因吗？
![image](https://github.com/xyjigsaw/CENET/assets/51685102/5e9557af-b952-43a9-a6f4-8fd8ae5e0405)

**Comment by xyjigsaw** [comment]
对看上去是读取文件的问题，但是按照requirements来配置python3.8的环境一般不会出问题。文件本身没有问题。

**Comment by goodboy-yuan** [comment]
环境版本的配置和requirements上一样 用的也是python3.8 是不是没有对数据集都处理好的原因（基于事件的icews14和18、GDELT没处理太大）
