### ISSUE TITLE
Failed to prepare history graph

### ISSUE THREAD

**Issue by passermyh** [xyjigsaw/CENET#20]
Thanks for your work!
However I couldn't get the data successfully.
![图片](https://github.com/xyjigsaw/CENET/assets/71198047/849cd90d-0c60-453f-93fe-af395083f954)
Here's the device I use
![图片](https://github.com/xyjigsaw/CENET/assets/71198047/bb984dec-9b6e-4ccb-9bec-88c99d5f6ef2)
What should I do?

**Comment by xyjigsaw** [comment]
Hi, there,
Sorry for any inconvenience caused to your operation. We generate historical information based on the RE-NET (Recurrent Event Network: Autoregressive Structure Inference over Temporary Knowledge Graphs) data preprocessing function. The code has not been optimized yet, and we do need to use large memory to generate data. If you have optimized the code, we look forward to your sharing/pushing with us in the Github repository.
Best wishes
