### ISSUE TITLE
Request for the evaluation of RE-GCN

### ISSUE THREAD

**Issue by KcAcoZhang** [xyjigsaw/CENET#24]
同学您好，由于计算指标的方式不同，请问CENET论文中汇报的RE-GCN结果是如何得到的呢？非常感谢您的帮助

**Comment by ayuhanga** [comment]
同学打扰你了，你复现这篇文章了吗，请问这个代码想跑起来，环境配置都需要什么呀？非常感谢！

**Comment by ZifengDing** [comment]
> 同学您好，由于计算指标的方式不同，请问CENET论文中汇报的RE-GCN结果是如何得到的呢？非常感谢您的帮助

用RE-GCN的utils里的sort_and_rank_filter做evaluation就可以了。这个函数用来做time-unaware filter的。

**Comment by ZifengDing** [comment]
> > 同学您好，由于计算指标的方式不同，请问CENET论文中汇报的RE-GCN结果是如何得到的呢？非常感谢您的帮助
> 
> 用RE-GCN的utils里的sort_and_rank_filter做evaluation就可以了。这个函数用来做time-unaware filter的。

仔细看了下代码，其实只要改一下forward和link_predict这两个函数就可以做time-aware filter了。把timestamp放到filtering里

**Comment by KcAcoZhang** [comment]
> > > 同学您好，由于计算指标的方式不同，请问CENET论文中汇报的RE-GCN结果是如何得到的呢？非常感谢您的帮助
> > 
> > 
> > 用RE-GCN的utils里的sort_and_rank_filter做evaluation就可以了。这个函数用来做time-unaware filter的。
> 
> 仔细看了下代码，其实只要改一下forward和link_predict这两个函数就可以做time-aware filter了。把timestamp放到filtering里

嗯嗯，我按照sort_and_rank_filter实现了，十分感谢
