### ISSUE TITLE
Validation set

### ISSUE THREAD

**Issue by XIAO-HOU** [xyjigsaw/CENET#3]
Excellent work!
I have some questions about the code. The validation set is not used, right?

https://github.com/xyjigsaw/CENET/blob/68a564afe1011b523d8c888fff9c165816f8e578/main.py#L213

**Comment by xyjigsaw** [comment]
Thank you for your attention. Sorry for that there are a few differences between the cleaned published codes and our original codes. The final seleted models are based on the results on the validation set.
