### ISSUE TITLE
代码中没有该对应函数问题

### ISSUE THREAD

**Issue by goodboy-yuan** [xyjigsaw/CENET#7]
def link_predict(self, nce_loss, preds, ce_loss, actor1, actor2, r, trust_musk, all_triples, pred_known, oracle,
                     history_tag=None, case_study=False):
        if case_study:
            f = open("case_study.txt", "a+")
            entity2id, relation2id = get_entity_relation_set(self.args.dataset)

        if oracle:
            preds = torch.mul(preds, trust_musk)
            print('$Batch After Oracle accuracy:', end=' ')
        else:
            print('$Batch No Oracle accuracy:', end=' ')
您好我在部署代码的时候get_entity_relation_se这个报错  没有找到该对应的函数是什么原因呢

**Comment by xyjigsaw** [comment]
Sorry for that, it is used for case study, you can safely remove them.

**Comment by goodboy-yuan** [comment]
好的谢谢   还有一个小问题您的这个数据处理完的文件train_graphs.txt在pycharm中的编码格式是哪种呢
