### ISSUE TITLE
文件编码格式

### ISSUE THREAD

**Issue by goodboy-yuan** [xyjigsaw/CENET#8]
有一个小问题您的这个数据处理完的文件train_graphs.txt在pycharm中的编码格式是哪种呢

**Comment by goodboy-yuan** [comment]
类似于这种的文件格式

**Comment by xyjigsaw** [comment]
抱歉给你带来了困惑，这里的文件后缀名不应该用txt，它是pickle格式。

**Comment by xyjigsaw** [comment]
我不太清楚pycharm里面是什么格式。

**Comment by goodboy-yuan** [comment]
您好，请问这种编码格式会影响到程序的读取执行吗？

**Comment by xyjigsaw** [comment]
不会的
